// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qcffnueckcyhgmzosooy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjZmZudWVja2N5aGdtem9zb295Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0OTgxODAsImV4cCI6MjA2NTA3NDE4MH0.03-pDWzivWR6hUVy-WqEba5iFvNRTNQOXlBP9EWaZ9U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);